apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    workspace-name: {{ .Release.Name }}
type: Opaque
data:
  ssh-host-rsa-key: "{{genPrivateKey "rsa" | b64enc}}"
  ssh-host-ecdsa-key: "{{genPrivateKey "ecdsa" | b64enc}}"