apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: NodePort
  selector:
    workspace-name: {{ .Release.Name }}
  ports:
    - port: 2222
      targetPort: 2222