#!/usr/bin/with-contenv bash

if [ ! -f /opt/ssh/sshd_config ];then
    echo "Copy sshd_config..."
    cp /tmp/sshd_config /opt/ssh/sshd_config
fi

if [ ! -d /opt/ssh/ssh_host_keys ]; then
    echo "Generating ssh host key folder"
    mkdir -p /opt/ssh/ssh_host_keys
fi

if [ ! -f /opt/ssh/ssh_host_keys/ssh_host_rsa_key ];then
    echo "Generating rsa host key"
    ssh-keygen -q -N "" -t rsa -b 4096 -f /opt/ssh/ssh_host_keys/ssh_host_rsa_key
fi

if [ ! -f /opt/ssh/ssh_host_keys/ssh_host_ecdsa_key ];then
    echo "Generating ecdsa hostkey"
    ssh-keygen -q -N "" -t ecdsa -f /opt/ssh/ssh_host_keys/ssh_host_ecdsa_key
fi